spring:
  datasource:
    url: jdbc:mysql://localhost/vbank_prod
    driverClassName: com.mysql.jdbc.Driver
    username: vbank
    password: 1234
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
