spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    username: vbank
    password: 1234
  jpa:
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
---

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost/vbank_dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
---

spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost/vbank_prod
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
---

spring:
  profiles: test
  datasource:
    url: jdbc:mysql://localhost/vbank_test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update