spring:
  datasource:
    url: jdbc:mysql://localhost/vbank_dev
    driverClassName: com.mysql.jdbc.Driver
    username: vbank
    password: 1234
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
